# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Continuous Development (CD)

on:
  workflow_run:
    workflows: ['Continuous Integration (CI)']
    types:
      - completed
  push:
    branches: ['main']
env:
  VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
  VITE_FIREBASE_AUTH_DOMAIN: ${{ vars.VITE_FIREBASE_AUTH_DOMAIN}}
  VITE_FIREBASE_PROJECT_ID: ${{vars.VITE_FIREBASE_PROJECT_ID}}
<<<<<<< HEAD
  VITE_FIRBASE_STORAGE_BUCKET: ${{vars.VITE_FIREBASE_STORAGE_BUCKET}}
=======
  VITE_FIREBASE_STORAGE_BUCKET: ${{vars.VITE_FIREBASE_STORAGE_BUCKET}}
>>>>>>> 4bfbb083ba8fee3be86e96db4e3926afcbbb7c2e
  VITE_FIREBASE_MESSAGING_SENDER_ID: ${{vars.VITE_FIREBASE_MESSAGING_SENDER_ID}}
  VITE_FIREBASE_APP_ID: ${{vars.VITE_FIREBASE_APP_ID}}
  VITE_FIREBASE_MEASUREMENT_ID: ${{vars.VITE_FIREBASE_MEASUREMENT_ID}}
  
jobs:
  production:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
        env:
          CI: false
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AWESOME_RENTING }}'
          channelId: live
          projectId: awesome-renting
