# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Continuous Development (CD)

on:
  workflow_run:
    workflows: ['Continuous Integration (CI)']
    types:
      - completed
  push:
    branches: ['main']
env:
  REACT_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
  REACT_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
  REACT_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
jobs:
  production:
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo $REACT_FIREBASE_API_KEY $REACT_FIREBASE_AUTH_DOMAIN $REACT_FIREBASE_PROJECT_ID
      - run: npm install
      - run: npm run build
        env:
          CI: false
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AWESOME_RENTING }}'
          channelId: live
          projectId: awesome-renting
