  name: Deploy to Firebase Hosting on merge
'on':
  workflow_run:
    workflows: ['Continuous Integration (CI)']
    # Execute the workflow once the CI workflow is completed on main branch.
    types:
      - completed
  push:
    branches:
      - main
env:
  VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
  VITE_FIREBASE_AUTH_DOMAIN: ${{ vars.VITE_FIREBASE_AUTH_DOMAIN}}
  VITE_FIREBASE_PROJECT_ID: ${{vars.VITE_FIREBASE_PROJECT_ID}}
  VITE_FIRBASE_STORAGE_BUCKET: ${{vars.VITE_FIREBASE_STORAGE_BUCKET}}
  VITE_FIREBASE_MESSAGING_SENDER_ID: ${{vars.VITE_FIREBASE_MESSAGING_SENDER_ID}}
  VITE_FIREBASE_APP_ID: ${{vars.VITE_FIREBASE_APP_ID}}
  VITE_FIREBASE_MEASUREMENT_ID: ${{vars.VITE_FIREBASE_MEASUREMENT_ID}}
jobs:
  staging:
    runs-on: ubuntu-latest
    environment:
      name: Development
    steps:
      - uses: actions/checkout@v3
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AWESOME_RENTING }}'
          channelId: live
          projectId: awesome-renting
  production:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AWESOME_RENTING }}'
          channelId: live
          projectId: awesome-renting
