name: Deploy to Firebase Hosting on merge
'on':
  workflow_run:
    workflows: ['Continuous Integration (CI)']
    # Execute the workflow once the CI workflow is completed on main branch.
    types:
      - completed
  push:
    branches:
      - main
env:
  VITE_FIREBASE_API_KEY: ${{secrets.VITE_FIREBASE_API_KEY }}
  VITE_FIREBASE_AUTH_DOMAIN: ${{ vars.VITE_FIREBASE_AUTH_DOMAIN }}
  VITE_FIREBASE_PROJECT_ID: ${{ vars.VITE_FIREBASE_PROJECT_ID }}
  VITE_FIREBASE_STORAGE_BUCKET: ${{vars.VITE_FIREBASE_STORAGE_BUCKET}}
  VITE_APP_ID: ${{vars.VITE_FIREBASE_APP_ID}}
  VITE_FIREBASE_MESSAGING_SENDER: ${{vars.VITE_FIREBASE_MESSAGING_SENDER}}
  VITE_VITE_FIREBASE_MEASURMENT_ID: ${{vars.VITE_VITE_FIREBASE_MEASURMENT_ID}}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo $REACT_FIREBASE_API_KEY $REACT_FIREBASE_AUTH_DOMAIN $REACT_FIREBASE_PROJECT_ID
      - run: npm install
      - run: npm run build
        env:
          CI: false
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AWESOME_RENTING }}'
          channelId: live
          projectId: awesome-renting
